Console.WriteLine("Please, input b1:");
double b1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input k1:");
double k1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input b2:");
double b2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input k2:");
double k2 = Convert.ToDouble(Console.ReadLine());
double x = (b2 - b1) / (k1 - k2);
Console.WriteLine($"Точка пересечения: ({x};{k1*x + b1})");