Console.WriteLine("Please, input X for point A:");
double x1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input Y for point A: ");
double y1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input Z for point A: ");
double z1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input X for point B: ");
double x2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input Y for point B: ");
double y2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Please, input Z for point B: ");
double z2 = Convert.ToDouble(Console.ReadLine());
double DistanceBetweenTwoPoints = Math.Sqrt(Math.Pow((x2 - x1), 2) + Math.Pow((y2 - y1), 2) + Math.Pow((z2 - z1), 2));
Console.WriteLine($"The distanse is: {DistanceBetweenTwoPoints}");